# Generated by Amazon Q Terraform Generator
# Timestamp: 20250922_231947
# Application: spring-boot

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# VPC Module
module "vpc" {
  source = "./modules/vpc"

  project_name = var.project_name
  environment  = var.environment

  vpc_cidr                 = var.vpc_cidr
  availability_zones       = var.availability_zones
  public_subnet_cidrs      = var.public_subnet_cidrs
  eks_private_subnet_cidrs = var.eks_private_subnet_cidrs
  rds_private_subnet_cidrs = var.rds_private_subnet_cidrs
}

# EKS Module
module "eks" {
  source = "./modules/eks"

  project_name = var.project_name
  environment  = var.environment

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.eks_private_subnet_ids

  node_instance_type = var.node_instance_type
  node_desired_size  = 3
  node_max_size      = 5
  node_min_size      = 2
}

# RDS Module
module "rds" {
  source = "./modules/rds"

  project_name = var.project_name
  environment  = var.environment

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.rds_private_subnet_ids

  engine            = "mysql"
  instance_class    = var.db_instance_class
  allocated_storage = var.db_allocated_storage

  db_name     = var.db_name
  db_username = var.db_username
  db_password = var.db_password
}
